spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show_sql: true
        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_CONT_NAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: ${LXC_SERVER_PORT}

logging:
  level:
    org.springframework.web: WARN
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 36000000

cors:
  allowedOrigins: ${WEBUI_URL}

lxc:
  copy: lxc copy %s %s
  start: lxc start %s
  stop: lxc stop %s
  info: lxc info %s
  routing: lxc config device add %s %s_ssh proxy listen=tcp:0.0.0.0:%s connect=tcp:localhost:%s
  cmdRunner: sshpwd

ssh:
  server:
    ip: ${SSH_SERVER_IP}
    port: ${SSH_SERVER_PORT}
    key: ${SSH_SERVER_KEY}
    username: ${SSH_SERVER_USERNAME}
    password: ${SSH_SERVER_PASSWORD}
    parentName: ${SSH_SERVER_LXC_PARENT}
  lxc:
    port: ${SSH_LXC_PORT}
