spring:
  jpa:
    database: POSTGRESQL
    showSql: true
    generateDdl: true
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: create-drop
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show_sql: true
        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_CONT_NAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${LXC_SERVER_PORT}
  ssl:
    key-alias: ${SSL_KEY_ALIAS}
    key-store: ${SSL_KEY_STORE}
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}

logging:
  level:
    org.springframework.web: WARN
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

security:
  jwt:
    token:
      secretKey: ${JWT_SECRET}
      expireLength: 36000

cors:
  allowedOrigins: '*'

lxc:
  copy: echo %s %s
  start: echo %s
  stop: echo %s
  info: echo info %s
  routing: echo config device add %s %s_ssh proxy listen=tcp:0.0.0.0:%s connect=tcp:localhost:%s
  cmdRunner: mock

init:
  addAdmin: false
  threadPoolSize: 2